import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

TRAINING_DATA = [
    ("kepala saya sakit sekali", "sakit_kepala"),
    ("kepala nyeri tidak tertahankan", "sakit_kepala"),
    ("migrain kambuh lagi", "sakit_kepala"),
    ("kepala berdenyut terus menerus", "sakit_kepala"),
    ("nyeri kepala sebelah kiri", "sakit_kepala"),
    ("kepala terasa berat banget", "sakit_kepala"),
    ("sering sakit kepala pagi hari", "sakit_kepala"),
    ("kepala sakit saat bangun tidur", "sakit_kepala"),
    ("obat sakit kepala yang bagus", "sakit_kepala"),
    ("kenapa kepala cenat cenut terus", "sakit_kepala"),
    ("sakit kepala tidak sembuh seminggu", "sakit_kepala"),
    ("kepala nyeri setelah begadang", "sakit_kepala"),
    ("kepala sakit setelah menatap layar", "sakit_kepala"),
    ("penyebab sakit kepala berulang", "sakit_kepala"),
    ("kepala sakit bagian belakang", "sakit_kepala"),
    ("cara mengobati sakit kepala alami", "sakit_kepala"),
    ("kepala pusing dan nyeri bersamaan", "sakit_kepala"),
    ("sakit kepala karena tekanan darah", "sakit_kepala"),
    ("kepala sakit tidak bisa kerja", "sakit_kepala"),
    ("kepala nyeri saat batuk", "sakit_kepala"),
    ("saya pusing tidak bisa berdiri", "pusing"),
    ("kepala berputar putar terus", "pusing"),
    ("vertigo saya kambuh lagi", "pusing"),
    ("sempoyongan saat berjalan", "pusing"),
    ("tiba tiba pusing dan mau jatuh", "pusing"),
    ("pusing saat berdiri dari duduk", "pusing"),
    ("kenapa saya sering pusing", "pusing"),
    ("kepala melayang tidak karuan", "pusing"),
    ("pusing setelah minum obat", "pusing"),
    ("pusing saat lapar", "pusing"),
    ("vertigo cara mengobatinya", "pusing"),
    ("pusing disertai telinga berdenging", "pusing"),
    ("pusing setelah bangun tidur", "pusing"),
    ("kepala oleng saat berjalan", "pusing"),
    ("pusing karena kurang darah", "pusing"),
    ("saya demam sudah 3 hari", "demam"),
    ("badan panas tidak turun turun", "demam"),
    ("suhu tubuh 38 derajat", "demam"),
    ("anak demam tinggi malam ini", "demam"),
    ("cara menurunkan demam tinggi", "demam"),
    ("demam disertai menggigil", "demam"),
    ("badan meriang dan lemas", "demam"),
    ("suhu badan naik terus", "demam"),
    ("obat demam untuk orang dewasa", "demam"),
    ("demam naik turun sudah seminggu", "demam"),
    ("badan panas tidak berkeringat", "demam"),
    ("cara kompres demam yang benar", "demam"),
    ("demam setelah hujan hujan", "demam"),
    ("panas badan disertai sakit kepala", "demam"),
    ("demam 39 derajat berbahaya tidak", "demam"),
    ("badan panas dingin bergantian", "demam"),
    ("demam pada anak cara mengatasi", "demam"),
    ("suhu tubuh normal berapa derajat", "demam"),
    ("demam disertai ruam di kulit", "demam"),
    ("cara cek suhu badan tanpa termometer", "demam"),
    ("hidung saya meler terus", "flu"),
    ("kena flu sudah 3 hari", "flu"),
    ("pilek tidak sembuh sembuh", "flu"),
    ("sering bersin bersin pagi hari", "flu"),
    ("masuk angin dan badan lemas", "flu"),
    ("hidung tersumbat susah bernapas", "flu"),
    ("obat pilek yang ampuh", "flu"),
    ("flu disertai sakit kepala", "flu"),
    ("influenza cara mengobatinya", "flu"),
    ("hidung berair terus menerus", "flu"),
    ("pilek sudah seminggu belum sembuh", "flu"),
    ("cara mencegah flu di musim hujan", "flu"),
    ("ingus berwarna hijau berbahaya tidak", "flu"),
    ("hidung mampet sebelah cara mengobati", "flu"),
    ("flu beda dengan pilek biasa", "flu"),
    ("batuk tidak berhenti sudah lama", "batuk"),
    ("batuk berdahak sudah seminggu", "batuk"),
    ("tenggorokan gatal dan batuk terus", "batuk"),
    ("batuk kering malam hari", "batuk"),
    ("cara menghilangkan batuk cepat", "batuk"),
    ("obat batuk yang efektif", "batuk"),
    ("batuk berdarah berbahaya tidak", "batuk"),
    ("batuk tidak sembuh sudah sebulan", "batuk"),
    ("batuk setelah minum air dingin", "batuk"),
    ("batuk berdahak warna kuning", "batuk"),
    ("batuk terus menerus saat malam", "batuk"),
    ("penyebab batuk tidak berhenti", "batuk"),
    ("batuk disertai demam dan pilek", "batuk"),
    ("obat batuk alami dari jahe", "batuk"),
    ("batuk pada anak cara mengatasi", "batuk"),
    ("cara meredakan batuk kering", "batuk"),
    ("batuk sampai sesak napas", "batuk"),
    ("batuk setelah olahraga kenapa", "batuk"),
    ("batuk berdahak hijau artinya apa", "batuk"),
    ("batuk kronis sudah lama", "batuk"),
    ("mual terus tidak mau makan", "mual"),
    ("perut tidak enak mau muntah", "mual"),
    ("mual setiap pagi hari", "mual"),
    ("kenapa mual setelah makan", "mual"),
    ("cara mengatasi mual saat hamil", "mual"),
    ("mual dan pusing bersamaan", "mual"),
    ("mual saat naik kendaraan", "mual"),
    ("mual setelah minum obat", "mual"),
    ("obat mual yang ampuh", "mual"),
    ("mual tanpa muntah penyebabnya", "mual"),
    ("mual di pagi hari terus", "mual"),
    ("mual dan tidak nafsu makan", "mual"),
    ("cara menghilangkan mual alami", "mual"),
    ("mual disertai keringat dingin", "mual"),
    ("mual setelah makan makanan berminyak", "mual"),
    ("diare sudah 2 hari", "diare"),
    ("mencret tidak berhenti", "diare"),
    ("BAB cair terus menerus", "diare"),
    ("diare dengan darah berbahaya tidak", "diare"),
    ("cara mengatasi diare cepat", "diare"),
    ("oralit untuk diare berapa sachet", "diare"),
    ("diare setelah makan seafood", "diare"),
    ("diare disertai kram perut", "diare"),
    ("diare pada anak cara mengatasi", "diare"),
    ("makanan untuk penderita diare", "diare"),
    ("diare lebih dari 3 hari berbahaya", "diare"),
    ("buang air besar cair terus menerus", "diare"),
    ("diare dan muntah bersamaan", "diare"),
    ("obat diare yang paling ampuh", "diare"),
    ("penyebab diare setelah makan pedas", "diare"),
    ("perut sakit melilit terus", "sakit_perut"),
    ("maag saya kambuh lagi", "sakit_perut"),
    ("lambung sakit setelah telat makan", "sakit_perut"),
    ("perut kembung dan begah", "sakit_perut"),
    ("nyeri ulu hati tidak tertahankan", "sakit_perut"),
    ("kram perut bagian bawah", "sakit_perut"),
    ("perut sakit setelah makan pedas", "sakit_perut"),
    ("cara mengatasi maag kambuh", "sakit_perut"),
    ("perut bunyi terus dan sakit", "sakit_perut"),
    ("asam lambung naik gejalanya", "sakit_perut"),
    ("sakit perut sebelah kiri bawah", "sakit_perut"),
    ("obat maag yang paling bagus", "sakit_perut"),
    ("nyeri perut tengah malam", "sakit_perut"),
    ("perut sakit setelah minum kopi", "sakit_perut"),
    ("perut terasa penuh dan begah", "sakit_perut"),
    ("saya sangat stres dengan pekerjaan", "stres"),
    ("pikiran kacau tidak bisa fokus", "stres"),
    ("tertekan dan tidak tenang", "stres"),
    ("cara menghilangkan stres cepat", "stres"),
    ("stres berat sampai tidak bisa tidur", "stres"),
    ("banyak pikiran dan gelisah terus", "stres"),
    ("beban hidup terlalu berat", "stres"),
    ("stres karena masalah keluarga", "stres"),
    ("stres kerja cara mengatasinya", "stres"),
    ("cara relaksasi saat stres berat", "stres"),
    ("stres membuat badan sakit", "stres"),
    ("terlalu banyak pikiran susah fokus", "stres"),
    ("merasa tertekan setiap hari", "stres"),
    ("cara kelola stres dengan baik", "stres"),
    ("stres akibat masalah finansial", "stres"),
    ("saya cemas berlebihan terus", "cemas"),
    ("anxiety attack cara mengatasinya", "cemas"),
    ("serangan panik tiba tiba", "cemas"),
    ("takut berlebihan tanpa alasan", "cemas"),
    ("gugup dan cemas setiap hari", "cemas"),
    ("overthinking tidak bisa berhenti", "cemas"),
    ("was was terus tidak tenang", "cemas"),
    ("rasa cemas yang tidak wajar", "cemas"),
    ("jantung berdebar karena cemas", "cemas"),
    ("cemas menghadapi sesuatu yang besar", "cemas"),
    ("cara mengatasi kecemasan berlebih", "cemas"),
    ("cemas dan panik tanpa sebab", "cemas"),
    ("phobia cara mengatasinya", "cemas"),
    ("cemas terus setiap hari kenapa", "cemas"),
    ("gangguan kecemasan cara pengobatan", "cemas"),
    ("susah tidur sampai subuh", "insomnia"),
    ("tidak bisa tidur setiap malam", "insomnia"),
    ("insomnia sudah berbulan bulan", "insomnia"),
    ("sering terbangun tengah malam", "insomnia"),
    ("begadang terus tidak bisa tidur", "insomnia"),
    ("cara mengatasi insomnia alami", "insomnia"),
    ("tidur tidak nyenyak terus", "insomnia"),
    ("susah tidur meski lelah", "insomnia"),
    ("cara agar cepat tidur malam", "insomnia"),
    ("tidak mengantuk meski sudah larut", "insomnia"),
    ("cara memperbaiki jam tidur", "insomnia"),
    ("penyebab susah tidur di malam hari", "insomnia"),
    ("obat tidur alami tanpa efek samping", "insomnia"),
    ("insomnia karena pikiran banyak", "insomnia"),
    ("tidur sedikit tapi tidak mengantuk", "insomnia"),
    ("cara meningkatkan daya tahan tubuh", "imunitas"),
    ("sering sakit flu apa yang kurang", "imunitas"),
    ("makanan untuk tingkatkan imun tubuh", "imunitas"),
    ("kenapa mudah sakit setiap musim hujan", "imunitas"),
    ("suplemen untuk imunitas tubuh terbaik", "imunitas"),
    ("cara agar tidak mudah sakit", "imunitas"),
    ("imunitas rendah gejalanya apa", "imunitas"),
    ("vitamin untuk meningkatkan imun", "imunitas"),
    ("olahraga untuk meningkatkan daya tahan", "imunitas"),
    ("makanan yang meningkatkan kekebalan tubuh", "imunitas"),
    ("cara menjaga imunitas di musim dingin", "imunitas"),
    ("tubuh lemas dan mudah sakit terus", "imunitas"),
    ("bawang putih untuk imunitas benar tidak", "imunitas"),
    ("cara meningkatkan imun secara alami", "imunitas"),
    ("daya tahan tubuh lemah cara mengatasinya", "imunitas"),
    ("dosis paracetamol untuk dewasa", "obat"),
    ("cara minum ibuprofen yang benar", "obat"),
    ("efek samping amoxicillin apa saja", "obat"),
    ("obat apa untuk menurunkan demam", "obat"),
    ("boleh tidak minum 2 obat bersamaan", "obat"),
    ("paracetamol diminum berapa kali sehari", "obat"),
    ("obat antibiotik harus habis tidak", "obat"),
    ("obat apa untuk sakit kepala ringan", "obat"),
    ("cara simpan obat yang benar", "obat"),
    ("obat generik sama efektif tidak", "obat"),
    ("boleh minum obat saat perut kosong", "obat"),
    ("dosis ibuprofen untuk anak", "obat"),
    ("obat kedaluwarsa masih boleh diminum", "obat"),
    ("cara membaca aturan pakai obat", "obat"),
    ("efek samping obat lambung", "obat"),
    ("vitamin c berapa mg per hari", "vitamin"),
    ("suplemen zinc manfaatnya apa", "vitamin"),
    ("omega 3 untuk kesehatan manfaatnya", "vitamin"),
    ("vitamin d kekurangan gejalanya apa", "vitamin"),
    ("multivitamin perlu diminum setiap hari", "vitamin"),
    ("vitamin b12 kekurangan gejalanya", "vitamin"),
    ("suplemen kolagen manfaatnya", "vitamin"),
    ("probiotik untuk kesehatan usus", "vitamin"),
    ("vitamin e untuk kulit manfaatnya", "vitamin"),
    ("kekurangan zat besi gejalanya apa", "vitamin"),
    ("vitamin untuk ibu hamil yang penting", "vitamin"),
    ("suplemen kalsium untuk tulang", "vitamin"),
    ("vitamin c alami dari makanan apa", "vitamin"),
    ("manfaat minum vitamin d setiap hari", "vitamin"),
    ("suplemen untuk energy dan stamina", "vitamin"),
    ("olahraga apa yang bagus untuk jantung", "olahraga"),
    ("berapa lama olahraga yang ideal per hari", "olahraga"),
    ("cara mulai olahraga untuk pemula", "olahraga"),
    ("nyeri otot setelah olahraga normal tidak", "olahraga"),
    ("olahraga untuk menurunkan tekanan darah", "olahraga"),
    ("yoga manfaatnya untuk kesehatan apa", "olahraga"),
    ("olahraga ringan untuk orang tua", "olahraga"),
    ("berapa kali seminggu harus olahraga", "olahraga"),
    ("olahraga saat puasa boleh tidak", "olahraga"),
    ("jenis olahraga untuk bakar lemak", "olahraga"),
    ("olahraga untuk mengurangi stres", "olahraga"),
    ("cara pemanasan sebelum olahraga", "olahraga"),
    ("olahraga pagi vs sore mana lebih baik", "olahraga"),
    ("olahraga untuk penderita diabetes", "olahraga"),
    ("jogging berapa km untuk pemula", "olahraga"),
    ("makanan apa yang sehat untuk jantung", "nutrisi"),
    ("pola makan sehat yang dianjurkan dokter", "nutrisi"),
    ("gizi seimbang untuk orang dewasa", "nutrisi"),
    ("makanan tinggi protein selain daging", "nutrisi"),
    ("diet sehat untuk penderita diabetes", "nutrisi"),
    ("makanan yang harus dihindari penderita hipertensi", "nutrisi"),
    ("pola makan untuk menurunkan kolesterol", "nutrisi"),
    ("makanan untuk kesehatan otak", "nutrisi"),
    ("buah yang paling banyak vitamin c", "nutrisi"),
    ("makanan untuk menjaga kesehatan ginjal", "nutrisi"),
    ("cara makan sehat dengan budget terbatas", "nutrisi"),
    ("sayuran yang paling bergizi untuk dikonsumsi", "nutrisi"),
    ("pola makan intermittent fasting itu apa", "nutrisi"),
    ("makanan fermentasi manfaatnya apa", "nutrisi"),
    ("diet mediterania itu seperti apa", "nutrisi"),
    ("berapa jam tidur yang cukup untuk dewasa", "tidur"),
    ("tidur siang baik tidak untuk kesehatan", "tidur"),
    ("cara memperbaiki kualitas tidur malam", "tidur"),
    ("kurang tidur efeknya apa saja", "tidur"),
    ("tidur larut malam berbahaya tidak", "tidur"),
    ("posisi tidur yang benar untuk punggung", "tidur"),
    ("kenapa sering mimpi buruk", "tidur"),
    ("tidur terlalu banyak berbahaya tidak", "tidur"),
    ("cara tidur nyenyak tanpa obat", "tidur"),
    ("waktu tidur terbaik untuk kesehatan", "tidur"),
    ("kenapa sering mengantuk meski sudah tidur", "tidur"),
    ("cara mengatur jam tidur yang benar", "tidur"),
    ("tidur sebelum jam 10 malam penting tidak", "tidur"),
    ("kualitas tidur buruk efeknya apa", "tidur"),
    ("sleep paralysis berbahaya tidak", "tidur"),
    ("badan pegal semua setelah kerja", "nyeri_otot"),
    ("nyeri sendi lutut saat naik tangga", "nyeri_otot"),
    ("asam urat kambuh cara mengobati", "nyeri_otot"),
    ("kram kaki tengah malam", "nyeri_otot"),
    ("otot tegang di leher dan bahu", "nyeri_otot"),
    ("pegal linu di seluruh badan", "nyeri_otot"),
    ("sendi kaku di pagi hari", "nyeri_otot"),
    ("nyeri otot setelah olahraga berat", "nyeri_otot"),
    ("cara menghilangkan pegal di punggung", "nyeri_otot"),
    ("rematik cara mengobatinya", "nyeri_otot"),
    ("nyeri pinggang bawah cara atasi", "nyeri_otot"),
    ("otot betis kram cara mengatasi", "nyeri_otot"),
    ("bahu kaku dan nyeri penyebabnya", "nyeri_otot"),
    ("asam urat tinggi makanan yang dihindari", "nyeri_otot"),
    ("nyeri sendi tangan cara mengobati", "nyeri_otot"),
    ("kulit gatal gatal tidak tahu sebabnya", "gatal"),
    ("biduran muncul tiba tiba", "gatal"),
    ("alergi kulit cara mengobatinya", "gatal"),
    ("ruam merah di kulit gatal", "gatal"),
    ("eksim di tangan kambuh lagi", "gatal"),
    ("kulit bentol setelah makan udang", "gatal"),
    ("gatal di seluruh badan malam hari", "gatal"),
    ("dermatitis cara mengobatinya", "gatal"),
    ("gatal di lipatan kulit", "gatal"),
    ("alergi dingin cara mengatasinya", "gatal"),
    ("kulit kering dan gatal cara atasi", "gatal"),
    ("gatal setelah makan obat", "gatal"),
    ("biduran hilang sendiri tidak", "gatal"),
    ("obat gatal yang aman", "gatal"),
    ("gatal karena keringat cara atasi", "gatal"),
]

NLP_RESPONSES = {
    "sakit_kepala": "Berdasarkan analisis NLP, kemungkinan kamu mengalami sakit kepala. Coba minum air putih 2 gelas, istirahat di tempat tenang, dan hindari layar. Minum paracetamol 500mg jika perlu. Jika berlanjut lebih dari 6 jam, segera ke dokter.",
    "pusing": "Analisis NLP mendeteksi gejala pusing atau vertigo. Duduk atau berbaring sejenak, hindari gerakan mendadak, dan minum air putih. Jika disertai muntah hebat, segera periksa ke dokter.",
    "demam": "Analisis NLP mendeteksi gejala demam. Kompres air hangat, minum banyak cairan, istirahat cukup. Paracetamol bisa membantu. Jika suhu lebih dari 39 derajat atau lebih dari 3 hari, segera ke dokter.",
    "flu": "Analisis NLP mendeteksi gejala flu atau pilek. Istirahat total, minum air hangat dan vitamin C. Flu virus biasanya sembuh 5-7 hari tanpa antibiotik.",
    "batuk": "Analisis NLP mendeteksi gejala batuk. Minum air hangat dengan madu, hindari udara dingin. Jika lebih dari 2 minggu atau ada darah, segera ke dokter.",
    "mual": "Analisis NLP mendeteksi gejala mual. Makan sedikit tapi sering, hindari makanan pedas dan berlemak. Jahe hangat bisa meredakan mual.",
    "diare": "Analisis NLP mendeteksi gejala diare. Segera minum oralit untuk mencegah dehidrasi. Makan makanan lunak seperti bubur dan pisang.",
    "sakit_perut": "Analisis NLP mendeteksi gejala sakit perut atau maag. Makan teratur, hindari makanan asam dan pedas. Antasida bisa membantu.",
    "stres": "Analisis NLP mendeteksi kondisi stres. Coba teknik pernapasan 4-7-8 dan luangkan waktu untuk relaksasi. Olahraga ringan juga sangat membantu.",
    "cemas": "Analisis NLP mendeteksi kondisi kecemasan. Coba teknik grounding 5-4-3-2-1 dan batasi kafein. Konsultasi psikolog jika mengganggu aktivitas sehari-hari.",
    "insomnia": "Analisis NLP mendeteksi kondisi insomnia. Matikan layar 1 jam sebelum tidur dan jaga jam tidur yang konsisten setiap hari.",
    "obat": "Analisis NLP mendeteksi pertanyaan tentang obat-obatan. Paracetamol 500mg maksimal 4x per hari, Ibuprofen 400mg maksimal 3x per hari selalu setelah makan.",
    "vitamin": "Analisis NLP mendeteksi pertanyaan tentang vitamin atau suplemen. Vitamin C 500-1000mg per hari, Vitamin D 400-800 IU per hari, Zinc 8-11mg per hari.",
    "imunitas": "Analisis NLP mendeteksi pertanyaan tentang imunitas. Tidur cukup, makan sayur dan buah, olahraga teratur, dan kelola stres untuk meningkatkan daya tahan tubuh.",
    "olahraga": "Analisis NLP mendeteksi pertanyaan tentang olahraga. WHO merekomendasikan 150 menit per minggu olahraga intensitas sedang. Mulai bertahap dan selalu pemanasan!",
    "tidur": "Analisis NLP mendeteksi pertanyaan tentang tidur. Orang dewasa butuh 7-9 jam tidur berkualitas. Konsisten di jam tidur dan bangun yang sama setiap hari.",
    "nutrisi": "Analisis NLP mendeteksi pertanyaan tentang nutrisi. Terapkan pola makan gizi seimbang: sayur, buah, protein, karbohidrat kompleks, dan 8 gelas air per hari.",
    "nyeri_otot": "Analisis NLP mendeteksi gejala nyeri otot atau sendi. Kompres hangat, pijat lembut, dan stretching ringan. Istirahat cukup dan minum air yang banyak.",
    "gatal": "Analisis NLP mendeteksi gejala gatal atau alergi kulit. Jangan digaruk! Kompres dingin dan antihistamin bisa membantu meredakan.",
}


class NLPHealthClassifier:
    def __init__(self):
        self.pipeline = Pipeline([
            ('tfidf', TfidfVectorizer(
                ngram_range=(1, 2),
                max_features=5000,
                min_df=1,
                analyzer='word',
                lowercase=True,
                sublinear_tf=True
            )),
            ('clf', MultinomialNB(alpha=0.5))
        ])
        self.label_encoder = LabelEncoder()
        self.is_trained = False
        self.accuracy = 0.0
        self.classes = []

    def preprocess(self, text):
        text = text.lower().strip()
        text = re.sub(r'[^\w\s]', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text

    def train(self):
        texts = [self.preprocess(item[0]) for item in TRAINING_DATA]
        labels = [item[1] for item in TRAINING_DATA]
        y = self.label_encoder.fit_transform(labels)
        self.classes = self.label_encoder.classes_
        X_train, X_test, y_train, y_test = train_test_split(
            texts, y, test_size=0.2, random_state=42, stratify=y
        )
        self.pipeline.fit(X_train, y_train)
        y_pred = self.pipeline.predict(X_test)
        self.accuracy = accuracy_score(y_test, y_pred)
        self.is_trained = True
        print(f"[NLP] Model dilatih! Akurasi: {self.accuracy:.2%} | Data: {len(texts)} | Kategori: {len(self.classes)}")
        return self.accuracy

    def predict(self, text, threshold=0.15):
        if not self.is_trained:
            return None, 0.0
        processed = self.preprocess(text)
        proba = self.pipeline.predict_proba([processed])[0]
        max_idx = np.argmax(proba)
        confidence = proba[max_idx]
        if confidence >= threshold:
            category = self.label_encoder.inverse_transform([max_idx])[0]
            return category, float(confidence)
        return None, float(confidence)

    def get_top_predictions(self, text, top_n=3):
        if not self.is_trained:
            return []
        processed = self.preprocess(text)
        proba = self.pipeline.predict_proba([processed])[0]
        top_indices = np.argsort(proba)[::-1][:top_n]
        return [{"category": self.label_encoder.inverse_transform([i])[0],
                 "confidence": round(float(proba[i]) * 100, 1)} for i in top_indices]

    def get_response(self, category):
        return NLP_RESPONSES.get(category, None)


nlp_classifier = NLPHealthClassifier()
nlp_classifier.train()
